server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/basic?serverTimezone=GMT%2B8&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true'
    username: admin
    password: admins
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration：
    map-underscore-to-camel-case: true
